### ISSUE TITLE
ebb/tests/test_ebb_pmu_clobber.c is clobbering an invalid register ?

### ISSUE THREAD

**Issue by tuliom** [paflib/paflib#10]
Here is the log:
{{{
gcc -DHAVE_CONFIG_H -I. -I/home/tuliom/src/paflib/ebb -I..  -I/home/tuliom/src/paflib/common -I/home/tuliom/src/paflib/ebb  -Wall -Werror -rdynamic -m32 -MT tests/test_ebb_pmu_clobber.o -MD -MP -MF $depbase.Tpo -c -o tests/test_ebb_pmu_clobber.o /home/tuliom/src/paflib/ebb/tests/test_ebb_pmu_clobber.c &&\
mv -f $depbase.Tpo $depbase.Po
/home/tuliom/src/paflib/ebb/tests/test_ebb_pmu_clobber.c: In function ‘core_busy_loop’:
/home/tuliom/src/paflib/ebb/tests/test_ebb_pmu_clobber.c:283:1: error: 31 cannot be used in asm here
 }
 ^
/home/tuliom/src/paflib/ebb/tests/test_ebb_pmu_clobber.c:283:1: error: 31 cannot be used in asm here
Makefile:865: recipe for target 'tests/test_ebb_pmu_clobber.o' failed
make[2]: *** [tests/test_ebb_pmu_clobber.o] Error 1
}}}

**Comment by pmur** [comment]
Should be fix in the changeset d6debd9..957da2e.
