### ISSUE TITLE
Tests fail to build with "-fPIC" option

### ISSUE THREAD

**Issue by jcajka** [paflib/paflib#11]
I have hit this issue in Fedora 23. IIRC since F22, hardened build is enabled for all packages by default, this adds "-fPIC" among other options. Removing the option "-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1" (it adds the "-fPIC") makes the tests compile(and pass without failure). I have used this workaround for "make check" in Fedora package.

Not sure but it might be related to the Issue #10.

Failed build: http://ppc.koji.fedoraproject.org/koji/taskinfo?taskID=2692226 (older version, in current version warnings are fixed, but the error persists)

Snip of build log:
.
.
.
libtool: link: gcc -Wall -rdynamic -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mcpu=power7 -mtune=power8 -Wl,-z -Wl,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o .libs/test_ebb_pmu_multi tests/test_ebb_pmu_multi.o tests/test_ebb_common.o  ./.libs/libpaf-ebb.so -lpthread
gcc -DHAVE_CONFIG_H -I. -I..  -I../common -I../ebb  -Wall -rdynamic -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mcpu=power7 -mtune=power8 -c -o tests/test_ebb_pmu_clobber.o tests/test_ebb_pmu_clobber.c
tests/test_ebb_pmu_clobber.c: In function 'ebb_test_pmu_clobber':
tests/test_ebb_pmu_clobber.c:54:3: error: PIC register clobbered by '30' in 'asm'
   asm volatile ("li  3,  0x3030\n"
   ^
.
.
.

**Comment by pmur** [comment]
This should now be fixed in the changeset d6debd9..957da2e
