### ISSUE TITLE
Adding changelog for each release

### ISSUE THREAD

**Issue by leitao** [paflib/paflib#4]
I understand that this library should have a changelog file describing the features for each release. This is also useful when making the package available in the distros, as Debian.

**Comment by tuliom** [comment]
What kind of formats does Debian accept?
Maybe 'git log v1..v2'?

**Comment by leitao** [comment]
Yes. Any format you find appropriate.

**Comment by tuliom** [comment]
This issue has been implemented in PR #8 .
